=== mike-marcacci/gandhi/lib/api/schemas/user.json
{
  "id": "http://www.gandhi.io/schema/user",
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": [
    "id",
    "email"
  ],
  "additionalProperties": false,
  "properties":{
    "admin": {
      "type": "boolean",
      "default": false
    },
    "email": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "default": ""
    },
    "password": {
      "type": "string",
      "minLength": 4
    },
    "recovery_token": {
      "type": ["null","string"],
      "default": null
    },
    "created": {
      "type": "number"
    },
    "updated": {
      "type": "number"
    },
    "preferences": {
      "type": "object",
      "default": {}
    }
  }
}

=== mike-marcacci/gandhi/test/fixtures/db/users.json
[{
	"recovery_token": null,
	"updated": 1407029321.882,
	"name": "Eric Jensen",
	"created": 1407029321.882,
	"admin": false,
	"id": "3cd2dc98-e280-4e72-a437-9a916d98b636",
	"password": "c2NyeXB0AA4AAAAIAAAAAfJfxQEzHBLEeh3eU5cNm3GkKHmAroIKbVQQl9KEFE7CmcbnNjKrAuahB0R5WrCjyGhV3ygzIaU2NhBxIScoQPG7wJP/N4nW91BNrPm4xue/",
	"email": "eric.jensen@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1407029321.882,
	"name": "Jon Ramos",
	"created": 1407029321.882,
	"admin": false,
	"id": "5a3cf444-9d87-4125-8026-2d5ffb834676",
	"password": "c2NyeXB0AA4AAAAIAAAAATZ/fO+WCFdWZ8CVN/tavTXX0WcFBCQDtzGZn6/nv0d6IBW8geom2/fQTVb4T0oPYd9Ze4baEKAWqU2PHU6oxBqhmj+kXf1CyBWTsCOUBFfP",
	"email": "jon.ramos@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1407029321.882,
	"name": "Michael Douglas",
	"created": 1407029321.882,
	"admin": false,
	"id": "72e7f9a1-614d-423e-8273-1194932f8718",
	"password": "c2NyeXB0AA8AAAAIAAAAAazOoRBesUNvcjIY6X2zSkOcY7LfHDj1ZNDK94tbdN3L6oG9bIi9jm4qsG2sAuEpffBpb8XuEATpReG5YIt1vL7dwlMttPrzGFq1EEKM4wbU",
	"email": "michael.douglas@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1407029321.882,
	"name": "Mark Boerneke",
	"created": 1407029321.882,
	"admin": false,
	"id": "82b08fd0-b93d-4169-a0bf-b25823077adb",
	"password": "c2NyeXB0AA4AAAAIAAAAAe/1UjL3qtgcQjKxswA1spbRkYInvpGu62YdiG2zfRjgUrxiI7KNWVBJkjlLEYUaSqputmF+RH+ugwQvu9UmZOU2cLMc5bNAxNA+ML/p1XXr",
	"email": "mark.boerneke@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": "c2NyeXB0AA4AAAAIAAAAARhyUZ+MHlSmwgVs1o7YLiDkNebjRGOKioaoaZ6TPdOuZx7u98nhtEaxeMhr8qaBscAqmvqLhhAA8V7vILvdLMC7oYEwB6cedX/AN89SvKLO",
	"updated": 1407029321.882,
	"name": "Dustin Towery",
	"created": 1407029321.882,
	"admin": false,
	"id": "847e085b-df0e-4dc7-9cbf-d485d6e2de96",
	"password": "c2NyeXB0AA8AAAAIAAAAAfXCOXrKklbdOscJOZcTgvn94drsvqOu5tf/fc7/AV6RrUHMJr1HvcuNUD2gbCTXZ9RYPbpX9liyh5FoWb9nVzsUx+luLAX42wsm1ukOBLb5",
	"email": "dustin.towery@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": "c2NyeXB0AA8AAAAIAAAAAUEmpTp68mfzMIQMlkUd3zqd4SZaQe1xDm32Dk/yH2dZ0GkrciH6KX6j9VAIMqgyuNuGZwapU+lj5h8QDOjr6YMHtT19dtrwE7RlNcwTjd1d",
	"updated": 1407029321.882,
	"name": "Tim Marcacci",
	"created": 1407029321.882,
	"admin": false,
	"id": "84fbaa78-54b0-42fc-9754-c9ea7dc24538",
	"password": "c2NyeXB0AA4AAAAIAAAAATA+dYEi/gYuTrBfkz2/kXbgLlh+H5d96Tdxab0+sZeupIuPLZG9SCY+FgW8OXUXL4KlJLOsKwoA3V2GYnfpp7Yt5OHDsfbHkDw+2XjL35T5",
	"email": "tim.marcacci@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1413168047.679,
	"name": "Emily Marcacci",
	"created": 1413163935.849,
	"admin": true,
	"id": "983e973c-2942-4b9d-b0a0-5fba5819a086",
	"password": "c2NyeXB0AA0AAAAIAAAAAdn49sXcp27dP7hYGsixIvJ7cS3wDjpjvKU45IV2O2hTMoS4xwdlPut8YDF58jJ8yWiWG8j/WqWifvr7dfzYXfXhvvj0V47+9AG79kIS0Kgq",
	"email": "emily.marcacci@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1413163935.849,
	"name": "Mike Marcacci",
	"created": 1413163935.849,
	"admin": true,
	"id": "a5901ab6-bf17-49cd-981d-c25875aec8e9",
	"password": "c2NyeXB0AA4AAAAIAAAAAXJUMPjPphkqlfeJ5X7Kx9EyRGQy/f74JOAS5zzEOVGsOL/Z2i/BjMz6rOn5pA2bIqyKcZfc8ipslSSZahvLteZ2ycnl3gSf2lqzdklnZyMA",
	"email": "mike.marcacci@test.gandhi.io",
	"preferences": {
		"admin": {
			"technical": true
		}
	}
}, {
	"recovery_token": null,
	"updated": 1413168024.813,
	"name": "Sol\u00e8ne Clavel",
	"created": 1413168024.813,
	"admin": false,
	"id": "cf237901-2890-439f-add3-dc641b867459",
	"password": "c2NyeXB0AA4AAAAIAAAAAU44kWTMUgf1DN2S9Cf8CtWJ2M6m3ulDCJ8PcB1oPzB8NLsYi+AXcXT9QU2yk4bEjWBIbraT9q55pcLVGPlgWYuz1PPCSRq8ObEMbRixfu7O",
	"email": "solene.clavel@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1413178783.345,
	"name": "Anna Ver Beek",
	"created": 1413178783.345,
	"admin": false,
	"id": "e3195f3f-94d8-41c8-a072-06d1aec2bb49",
	"password": "c2NyeXB0AA4AAAAIAAAAAZndA79OKICZkMN01oWH4pTsD5ssKFafubyWUkbUkXX4C0K8PBxeQ+1xzEMC20WdqBqvxejUko0JJP7tAGcXcnnlO3FKF4q0TvDBItgO2UvP",
	"email": "anna.verbeek@test.gandhi.io",
	"preferences": {}
}, {
	"recovery_token": null,
	"updated": 1407029321.882,
	"name": "Matt Shafer",
	"created": 1407029321.882,
	"admin": false,
	"id": "f6826282-1ffb-453d-8804-6b2921e6807f",
	"password": "c2NyeXB0AA4AAAAIAAAAAe6TqnGT43ChQ332QjkUCCHMYgXet95V5NlL3cw7xyZCf3P/OclO9vjqL1/QE+E42gKyCxWj2571hs/RrkBf+LCmpVIuhRIMhxYRUFwV9qW4",
	"email": "matt.shafer@test.gandhi.io",
	"preferences": {}
}]
